# This is a basic workflow to help you get started with Actions

name: Compiler

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'beta'
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    uses: ./.github/workflows/code.tester.yml
  testAvd:
    uses: ./.github/workflows/deploy.avd.env.yml
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  release:
    needs:
      - test
      - testAvd
    uses: ./.github/workflows/release.yml
  writeDocs:
      needs:
        - test
      uses: ./.github/workflows/docwriter.yml
  publish:
    if: |
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs:
      - writeDocs
      - test
      - testAvd
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: azModule
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Publishing module
        shell: pwsh
        run: |
          ./Compiler/Az.Avd.publishPSgallery.ps1 -PS_GALLERY_KEY ${{ secrets.PS_GALLERY_KEY }}